language: node_js
node_js:
- 12.16.0
branches:
  only:
  - master
git:
  depth: 1
cache:
  directories:
  - node_modules

before_install:
# ssh config
- openssl aes-256-cbc -K $encrypted_c4e4594cf959_key -iv $encrypted_c4e4594cf959_iv
  -in id_rsa.enc -out ~/.ssh/deploy_rsa -d
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
install:
- yarn install
script:
- yarn build
after_success:
# -r, --recursive 对子目录以递归模式处理
# -l, --links 保留软链接
# -p, --perms 保持文件权限
# -t, --times 保持文件时间信息
# -o, --owner 保持文件属主信息
# -g, --group 保持文件属组信息
# -D, --devices 保持设备文件信息
# -a, --archive 归档模式，表示以递归方式传输文件，并保持所有文件属性，等于-rlptgoD
# -v, --verbose 详细模式输出
# -z, --compress 对备份的文件在传输时进行压缩处理。
# --delete 删除那些 DST 中 SRC 没有的文件，可能会导致暂时的服务不可用
# --delete-after 传输结束以后再删除
# --progress 显示备份过程
# -e, --rsh=command 指定使用 rsh、ssh 方式进行数据同步。
- rsync -azv --delete-after --progress -e 'ssh -o stricthostkeychecking=no' public/ root@$DEPLOY_HOST:/data/charlesfeng/blog/
- rsync -azv --delete-after --progress -e 'ssh -o stricthostkeychecking=no' defaulterror/ root@$DEPLOY_HOST:/data/charlesfeng/defaulterror/
